jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # ou seu comando de build

      - name: Deploy
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git checkout gh-pages  # ou sua branch de destino
          rm -rf ./*
          cp -r ../dist/* ./
          git add .
          git commit -m "Deployed using GitHub Actions"
          git push origin gh-pages  # ou sua branch de destino
